##################################################################################
# STAGE 0 - base environment with first set of runtime dependencies
##################################################################################
FROM centos:centos7 as ${component}-base-env
LABEL ${component}-base-env="yes"
LABEL ${component}-build-env="no"
LABEL ${component}-build="no"
LABEL ${component}-test-env="no"
LABEL ${component}-main="no"
LABEL ${component}-dist="no"

RUN yum -y --enablerepo=extras install epel-release && \
    yum -y install https://repo.ius.io/ius-release-el7.rpm && \
    yum -y install http://repo.okay.com.mx/centos/7/x86_64/release/okay-release-1-5.el7.noarch.rpm && \
    yum clean all

##################################################################################
# STAGE 1 - build tools and libraries needed to build ${component}
##################################################################################
FROM ${component}-base-env as ${component}-build-env
LABEL ${component}-base-env="no"
LABEL ${component}-build-env="yes"
LABEL ${component}-build="no"
LABEL ${component}-test-env="no"
LABEL ${component}-main="no"
LABEL ${component}-dist="no"

# for compiling and unit testing
RUN yum -y install \
        cmake3 \
        gcc \
        gcc-c++ \
        gtest-devel \
        make \
        rpm-build && \
    yum clean all

ENTRYPOINT [ "bash" ]

##################################################################################
# STAGE 2 - the ${component} source and compiled binaries
##################################################################################
FROM ${component}-build-env as ${component}-build
LABEL ${component}-base-env="no"
LABEL ${component}-build-env="no"
LABEL ${component}-build="yes"
LABEL ${component}-test-env="no"
LABEL ${component}-main="no"
LABEL ${component}-dist="no"

# ADD . /${component}
# RUN cd /${component} && \
#     mkdir ./build && \
#     cd ./build && \
#     cmake3 \
#         -DCMAKE_INSTALL_PREFIX=/usr \
#         -DCMAKE_BUILD_TYPE=RelWithDebInfo \
#         -DCPACK_PACKAGE_DIRECTORY=/lhdist \
#         ../ && \
#     make && \
#     make test && \
#     make package \

##################################################################################
# STAGE 3 - the image with all built build/runtime dependencies, ${component} 
#           binaries and test binaries needed for running integration tests
##################################################################################
FROM ${component}-build as ${component}-test-env
LABEL ${component}-base-env="no"
LABEL ${component}-build-env="no"
LABEL ${component}-build="no"
LABEL ${component}-test-env="yes"
LABEL ${component}-main="no"
LABEL ${component}-dist="no"

# RUN cd /lhmiscutil/build && \
#     make install-lhmiscutil

##################################################################################
# STAGE 4 - the base image with additional built runtime dependencies and 
#           ${component} binaries includes nothing from build-env
##################################################################################
FROM ${component}-base-env as ${component}-main
LABEL ${component}-base-env="no"
LABEL ${component}-build-env="no"
LABEL ${component}-build="no"
LABEL ${component}-test-env="no"
LABEL ${component}-main="yes"
LABEL ${component}-dist="no"

# COPY --from=${component}-build /usr/ /usr/
# COPY --from=${component}-build /${component}/ /${component}/

##################################################################################
# STAGE 5 - the base image with /lhdist populated with custom packages required to
#           build ${component}
##################################################################################
FROM ${component}-base-env as ${component}-dist
LABEL ${component}-base-env="no"
LABEL ${component}-build-env="no"
LABEL ${component}-build="no"
LABEL ${component}-test-env="no"
LABEL ${component}-main="no"
LABEL ${component}-dist="yes"

COPY --from=${component}-build /lhdist/ /lhdist/