##################################################################################
# STAGE 0 - base environment with first set of runtime dependencies
##################################################################################
ARG BUILD_TAG
ARG GIT_COMMIT

FROM centos:centos7 as ${component}-base-env
ENV BUILD_TAG=${BUILD_TAG}
LABEL build_tag="${BUILD_TAG}"
ENV GIT_COMMIT=${GIT_COMMIT}
LABEL git_commit="${GIT_COMMIT}"

RUN yum -y --enablerepo=extras install epel-release && \
    yum -y install https://repo.ius.io/ius-release-el7.rpm && \
    yum -y install http://repo.okay.com.mx/centos/7/x86_64/release/okay-release-1-5.el7.noarch.rpm && \
    yum clean all

##################################################################################
# STAGE 1 - build tools and libraries needed to build ${component}
##################################################################################
FROM ${component}-base-env as ${component}-build-env

# for compiling and unit testing
RUN yum -y install \
        cmake3 \
        gcc \
        gcc-c++ \
        gtest-devel \
        make \
        rpm-build && \
    yum clean all

# ADD ./modules/lhscriptutil/scripts/refreshOrSetupLHDistYumRepo.sh /refreshOrSetupLHDistYumRepo.sh

ENTRYPOINT [ "bash" ]

##################################################################################
# STAGE 2 - the ${component} source and compiled binaries
##################################################################################
FROM ${component}-build-env as ${component}-build

# ADD . /${component}
# RUN cd /${component} && \
#     mkdir ./build && \
#     cd ./build && \
#     cmake3 \
#         -DCMAKE_INSTALL_PREFIX=/usr \
#         -DCMAKE_BUILD_TYPE=RelWithDebInfo \
#         -DCPACK_PACKAGE_DIRECTORY=/lhdist \
#         ../ && \
#     make && \
#     make test && \
#     make package \
# RUN /refreshOrSetupLHDistYumRepo.sh

##################################################################################
# STAGE 3 - the image with all built build/runtime dependencies, ${component} 
#           binaries and test binaries needed for running integration tests
##################################################################################
FROM ${component}-build as ${component}-test-env

# RUN cd /${component}/build && \
#     make install && \
#     ldconfig 

##################################################################################
# STAGE 4 - the base image with additional built runtime dependencies and 
#           ${component} binaries includes nothing from build-env
##################################################################################
FROM ${component}-base-env as ${component}-main

# COPY --from=${component}-build /etc/ /etc/
# COPY --from=${component}-build /opt/ /opt/
# COPY --from=${component}-build /usr/ /usr/
# COPY --from=${component}-build /${component}/ /${component}/
# RUN cd /${component}/build && \
#     make install && \
#     make package && \
#     ldconfig && \
#     cd / && \
#     rm -rf /${component}

##################################################################################
# STAGE 5 - the base image with /lhdist populated with custom packages required to
#           build ${component}
##################################################################################
FROM ${component}-base-env as ${component}-dist

COPY --from=${component}-build /lhdist/ /lhdist/