gitModulesCheckoutOutDirEnvVar = 'TILT_GIT_RESOURCE_CHECKOUT_DIR'
if os.getenv( gitModulesCheckoutOutDirEnvVar, default = None ) is None:
    os.putenv( gitModulesCheckoutOutDirEnvVar, os.path.abspath( "./modules" ) )
gitDir = os.getenv( gitModulesCheckoutOutDirEnvVar, default = None )
if gitDir is None:
    fail( "failed to set modules checkout dir" )

load("ext://git_resource", "git_checkout")

git_checkout( "git@github.com:fbuonaro/lhscriptutil.git#release/v/1.3.0" )
load( os.path.join( gitDir, "lhscriptutil", "tilt", "common", "Tiltfile"), "lhQuickBuildImage", "lhQuickBuildImageNoK8" )
load( os.path.join( gitDir, "lhscriptutil", "Tiltfile"), "cfg" )

lhQuickBuildImageNoK8( "${component}", cfg )